server:
  servlet:
    context-path: /api/v1/poli
  port: 9082
spring:
  application:
    name: shopping
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
